-- CBS Migration 000102: tabel referensi sandi OJK (Lampiran 02, 03, 05 SEOJK 16/2024).
-- Run after: 000101_rename_deposits_to_time_deposits.up.sql (urutan; tidak bergantung isinya).
--
-- Sumber: SEOJK No. 16/SEOJK.03/2024 "Pelaporan Melalui Sistem Pelaporan Otoritas Jasa
-- Keuangan dan Transparansi Kondisi Keuangan bagi Bank Perekonomian Rakyat" (PDF resmi
-- 528 hlm.). Diekstrak 26 Sep 2026 dari salinan PDF di luar repo (tidak di-commit).
--   * Lampiran 02 - Daftar Sandi Pihak Lawan    : PDF #page 303     -> ojk_pihak_lawan
--   * Lampiran 03 - Daftar Sandi Kabupaten/Kota : PDF #page 304-315 -> ojk_kabupaten
--   * Lampiran 05 - Daftar Sandi Sektor Ekonomi : PDF #page 322-419 -> ojk_sektor_ekonomi
--
-- Jumlah baris: ojk_pihak_lawan = 23; ojk_kabupaten = 514; ojk_sektor_ekonomi = 476.
--
-- Tabel referensi ini hanya menyimpan salinan sandi resmi; tidak mengubah perilaku
-- aplikasi. code = PRIMARY KEY, sehingga INSERT ... ON CONFLICT DO NOTHING membuat
-- pengisian ulang tidak menggandakan baris. Label Lampiran 05 adalah teks kolom LABEL
-- tanpa awalan hierarki (mis. "A.", "C.13.1") dan tanpa definisi panjang.
--
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS; INSERT ... ON CONFLICT DO NOTHING.

CREATE TABLE IF NOT EXISTS ojk_pihak_lawan (
    code  TEXT PRIMARY KEY,
    label TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ojk_kabupaten (
    code     TEXT PRIMARY KEY,
    label    TEXT NOT NULL,
    provinsi TEXT
);

CREATE TABLE IF NOT EXISTS ojk_sektor_ekonomi (
    code  TEXT PRIMARY KEY,
    label TEXT NOT NULL
);

COMMENT ON TABLE ojk_pihak_lawan IS
    'Daftar Sandi Pihak Lawan, Lampiran 02 SEOJK No. 16/SEOJK.03/2024 (PDF #page 303), 23 baris.';
COMMENT ON TABLE ojk_kabupaten IS
    'Daftar Sandi Kabupaten/Kota beserta provinsi, Lampiran 03 SEOJK No. 16/SEOJK.03/2024 (PDF #page 304-315), 514 baris.';
COMMENT ON TABLE ojk_sektor_ekonomi IS
    'Daftar Sandi Sektor Ekonomi, Lampiran 05 SEOJK No. 16/SEOJK.03/2024 (PDF #page 322-419), 476 baris.';

CREATE INDEX IF NOT EXISTS idx_ojk_pihak_lawan_label
    ON ojk_pihak_lawan (label);
CREATE INDEX IF NOT EXISTS idx_ojk_kabupaten_label
    ON ojk_kabupaten (label);
CREATE INDEX IF NOT EXISTS idx_ojk_kabupaten_provinsi
    ON ojk_kabupaten (provinsi);
CREATE INDEX IF NOT EXISTS idx_ojk_sektor_ekonomi_label
    ON ojk_sektor_ekonomi (label);

-- Lampiran 02 - Pihak Lawan (23 baris)
INSERT INTO ojk_pihak_lawan (code, label) VALUES
    ('001', 'Bank Indonesia'),
    ('600', 'BPR'),
    ('601', 'BPRS'),
    ('700', 'Bank umum'),
    ('701', 'Bank umum syariah'),
    ('901', 'Unit usaha syariah (KC syariah bank umum)'),
    ('800', 'Pemerintah Pusat'),
    ('805', 'Pemerintah Daerah'),
    ('831', 'BUMN yang melakukan usaha penjaminan kredit dengan memenuhi persyaratan sebagaimana POJK KPMM'),
    ('832', 'BUMN lain'),
    ('833', 'BUMD yang melakukan usaha penjaminan kredit dengan memenuhi persyaratan sebagaimana POJK KPMM'),
    ('834', 'BUMD lain'),
    ('835', 'Lainnya'),
    ('840', 'Sektor Pemerintah Campuran'),
    ('860', 'Perusahaan'),
    ('870', 'Koperasi'),
    ('872', 'Kelompok'),
    ('874', 'Pegawai/Pensiunan (PNS, TNI/POLRI, Lembaga Negara dan BUMN/BUMD) yang kreditnya memenuhi persyaratan'),
    ('875', 'Lainnya'),
    ('879', 'Swasta Lainnya'),
    ('880', 'Asuransi jiwa'),
    ('890', 'Asuransi kredit'),
    ('000', 'Tanpa penjamin')
ON CONFLICT (code) DO NOTHING;

-- Lampiran 03 - Kabupaten/Kota (514 baris; provinsi = pengelompok pada dokumen)
INSERT INTO ojk_kabupaten (code, label, provinsi) VALUES
    ('0102', 'Kab. Bekasi', 'Jawa Barat'),
    ('0103', 'Kab. Purwakarta', 'Jawa Barat'),
    ('0106', 'Kab. Karawang', 'Jawa Barat'),
    ('0108', 'Kab. Bogor', 'Jawa Barat'),
    ('0109', 'Kab. Sukabumi', 'Jawa Barat'),
    ('0110', 'Kab. Cianjur', 'Jawa Barat'),
    ('0111', 'Kab. Bandung', 'Jawa Barat'),
    ('0112', 'Kab. Sumedang', 'Jawa Barat'),
    ('0113', 'Kab. Tasikmalaya', 'Jawa Barat'),
    ('0114', 'Kab. Garut', 'Jawa Barat'),
    ('0115', 'Kab. Ciamis', 'Jawa Barat'),
    ('0116', 'Kab. Cirebon', 'Jawa Barat'),
    ('0117', 'Kab. Kuningan', 'Jawa Barat'),
    ('0118', 'Kab. Indramayu', 'Jawa Barat'),
    ('0119', 'Kab. Majalengka', 'Jawa Barat'),
    ('0121', 'Kab. Subang', 'Jawa Barat'),
    ('0122', 'Kab. Bandung Barat', 'Jawa Barat'),
    ('0123', 'Kab. Pangandaran', 'Jawa Barat'),
    ('0180', 'Kota Banjar', 'Jawa Barat'),
    ('0191', 'Kota Bandung', 'Jawa Barat'),
    ('0192', 'Kota Bogor', 'Jawa Barat'),
    ('0193', 'Kota Sukabumi', 'Jawa Barat'),
    ('0194', 'Kota Cirebon', 'Jawa Barat'),
    ('0195', 'Kota Tasikmalaya', 'Jawa Barat'),
    ('0196', 'Kota Cimahi', 'Jawa Barat'),
    ('0197', 'Kota Depok', 'Jawa Barat'),
    ('0198', 'Kota Bekasi', 'Jawa Barat'),
    ('0201', 'Kab. Lebak', 'Banten'),
    ('0202', 'Kab. Pandeglang', 'Banten'),
    ('0203', 'Kab. Serang', 'Banten'),
    ('0204', 'Kab. Tangerang', 'Banten'),
    ('0291', 'Kota Cilegon', 'Banten'),
    ('0292', 'Kota Tangerang', 'Banten'),
    ('0293', 'Kota Serang', 'Banten'),
    ('0294', 'Kota Tangerang Selatan', 'Banten'),
    ('0391', 'Wil. Kota Jakarta Pusat', 'DKI Jakarta'),
    ('0392', 'Wil. Kota Jakarta Utara', 'DKI Jakarta'),
    ('0393', 'Wil. Kota Jakarta Barat', 'DKI Jakarta'),
    ('0394', 'Wil. Kota Jakarta Selatan', 'DKI Jakarta'),
    ('0395', 'Wil. Kota Jakarta Timur', 'DKI Jakarta'),
    ('0396', 'Wil. Kepulauan Seribu', 'DKI Jakarta'),
    ('0501', 'Kab. Bantul', 'Daerah Istimewa Yogyakarta'),
    ('0502', 'Kab. Sleman', 'Daerah Istimewa Yogyakarta'),
    ('0503', 'Kab. Gunung Kidul', 'Daerah Istimewa Yogyakarta'),
    ('0504', 'Kab. Kulon Progo', 'Daerah Istimewa Yogyakarta'),
    ('0591', 'Kota Yogyakarta', 'Daerah Istimewa Yogyakarta'),
    ('0901', 'Kab. Semarang', 'Jawa Tengah'),
    ('0902', 'Kab. Kendal', 'Jawa Tengah'),
    ('0903', 'Kab. Demak', 'Jawa Tengah'),
    ('0904', 'Kab. Grobogan', 'Jawa Tengah'),
    ('0905', 'Kab. Pekalongan', 'Jawa Tengah'),
    ('0906', 'Kab. Tegal', 'Jawa Tengah'),
    ('0907', 'Kab. Brebes', 'Jawa Tengah'),
    ('0908', 'Kab. Pati', 'Jawa Tengah'),
    ('0909', 'Kab. Kudus', 'Jawa Tengah'),
    ('0910', 'Kab. Pemalang', 'Jawa Tengah'),
    ('0911', 'Kab. Jepara', 'Jawa Tengah'),
    ('0912', 'Kab. Rembang', 'Jawa Tengah'),
    ('0913', 'Kab. Blora', 'Jawa Tengah'),
    ('0914', 'Kab. Banyumas', 'Jawa Tengah'),
    ('0915', 'Kab. Cilacap', 'Jawa Tengah'),
    ('0916', 'Kab. Purbalingga', 'Jawa Tengah'),
    ('0917', 'Kab. Banjarnegara', 'Jawa Tengah'),
    ('0918', 'Kab. Magelang', 'Jawa Tengah'),
    ('0919', 'Kab. Temanggung', 'Jawa Tengah'),
    ('0920', 'Kab. Wonosobo', 'Jawa Tengah'),
    ('0921', 'Kab. Purworejo', 'Jawa Tengah'),
    ('0922', 'Kab. Kebumen', 'Jawa Tengah'),
    ('0923', 'Kab. Klaten', 'Jawa Tengah'),
    ('0924', 'Kab. Boyolali', 'Jawa Tengah'),
    ('0925', 'Kab. Sragen', 'Jawa Tengah'),
    ('0926', 'Kab. Sukoharjo', 'Jawa Tengah'),
    ('0927', 'Kab. Karanganyar', 'Jawa Tengah'),
    ('0928', 'Kab. Wonogiri', 'Jawa Tengah'),
    ('0929', 'Kab. Batang', 'Jawa Tengah'),
    ('0991', 'Kota Semarang', 'Jawa Tengah'),
    ('0992', 'Kota Salatiga', 'Jawa Tengah'),
    ('0993', 'Kota Pekalongan', 'Jawa Tengah'),
    ('0994', 'Kota Tegal', 'Jawa Tengah'),
    ('0995', 'Kota Magelang', 'Jawa Tengah'),
    ('0996', 'Kota Surakarta/Solo', 'Jawa Tengah'),
    ('1201', 'Kab. Gresik', 'Jawa Timur'),
    ('1202', 'Kab. Sidoarjo', 'Jawa Timur'),
    ('1203', 'Kab. Mojokerto', 'Jawa Timur'),
    ('1204', 'Kab. Jombang', 'Jawa Timur'),
    ('1205', 'Kab. Sampang', 'Jawa Timur'),
    ('1206', 'Kab. Pamekasan', 'Jawa Timur'),
    ('1207', 'Kab. Sumenep', 'Jawa Timur'),
    ('1208', 'Kab. Bangkalan', 'Jawa Timur'),
    ('1209', 'Kab. Bondowoso', 'Jawa Timur'),
    ('1211', 'Kab. Banyuwangi', 'Jawa Timur'),
    ('1212', 'Kab. Jember', 'Jawa Timur'),
    ('1213', 'Kab. Malang', 'Jawa Timur'),
    ('1214', 'Kab. Pasuruan', 'Jawa Timur'),
    ('1215', 'Kab. Probolinggo', 'Jawa Timur'),
    ('1216', 'Kab. Lumajang', 'Jawa Timur'),
    ('1217', 'Kab. Kediri', 'Jawa Timur'),
    ('1218', 'Kab. Nganjuk', 'Jawa Timur'),
    ('1219', 'Kab. Tulungagung', 'Jawa Timur'),
    ('1220', 'Kab. Trenggalek', 'Jawa Timur'),
    ('1221', 'Kab. Blitar', 'Jawa Timur'),
    ('1222', 'Kab. Madiun', 'Jawa Timur'),
    ('1223', 'Kab. Ngawi', 'Jawa Timur'),
    ('1224', 'Kab. Magetan', 'Jawa Timur'),
    ('1225', 'Kab. Ponorogo', 'Jawa Timur'),
    ('1226', 'Kab. Pacitan', 'Jawa Timur'),
    ('1227', 'Kab. Bojonegoro', 'Jawa Timur'),
    ('1228', 'Kab. Tuban', 'Jawa Timur'),
    ('1229', 'Kab. Lamongan', 'Jawa Timur'),
    ('1230', 'Kab. Situbondo', 'Jawa Timur'),
    ('1271', 'Kota Batu', 'Jawa Timur'),
    ('1291', 'Kota Surabaya', 'Jawa Timur'),
    ('1292', 'Kota Mojokerto', 'Jawa Timur'),
    ('1293', 'Kota Malang', 'Jawa Timur'),
    ('1294', 'Kota Pasuruan', 'Jawa Timur'),
    ('1295', 'Kota Probolinggo', 'Jawa Timur'),
    ('1296', 'Kota Blitar', 'Jawa Timur'),
    ('1297', 'Kota Kediri', 'Jawa Timur'),
    ('1298', 'Kota Madiun', 'Jawa Timur'),
    ('2301', 'Kab. Bengkulu Selatan', 'Bengkulu'),
    ('2302', 'Kab. Bengkulu Utara', 'Bengkulu'),
    ('2303', 'Kab. Rejang Lebong', 'Bengkulu'),
    ('2304', 'Kab. Lebong', 'Bengkulu'),
    ('2305', 'Kab. Kepahiang', 'Bengkulu'),
    ('2306', 'Kab. Mukomuko', 'Bengkulu'),
    ('2307', 'Kab. Seluma', 'Bengkulu'),
    ('2308', 'Kab. Kaur', 'Bengkulu'),
    ('2309', 'Kab. Bengkulu Tengah', 'Bengkulu'),
    ('2391', 'Kota Bengkulu', 'Bengkulu'),
    ('3101', 'Kab. Batanghari', 'Jambi'),
    ('3104', 'Kab. Sarolangun', 'Jambi'),
    ('3105', 'Kab. Kerinci', 'Jambi'),
    ('3106', 'Kab. Muaro Jambi', 'Jambi'),
    ('3107', 'Kab. Tanjung Jabung Barat', 'Jambi'),
    ('3108', 'Kab. Tanjung Jabung Timur', 'Jambi'),
    ('3109', 'Kab. Tebo', 'Jambi'),
    ('3111', 'Kab. Merangin', 'Jambi'),
    ('3112', 'Kab. Bungo', 'Jambi'),
    ('3191', 'Kota Jambi', 'Jambi'),
    ('3192', 'Kota Sungai Penuh', 'Jambi'),
    ('3201', 'Kab. Aceh Besar', 'Nanggroe Aceh Darussalam'),
    ('3202', 'Kab. Pidie', 'Nanggroe Aceh Darussalam'),
    ('3203', 'Kab. Aceh Utara', 'Nanggroe Aceh Darussalam'),
    ('3204', 'Kab. Aceh Timur', 'Nanggroe Aceh Darussalam'),
    ('3205', 'Kab. Aceh Selatan', 'Nanggroe Aceh Darussalam'),
    ('3206', 'Kab. Aceh Barat', 'Nanggroe Aceh Darussalam'),
    ('3207', 'Kab. Aceh Tengah', 'Nanggroe Aceh Darussalam'),
    ('3208', 'Kab. Aceh Tenggara', 'Nanggroe Aceh Darussalam'),
    ('3209', 'Kab. Aceh Singkil', 'Nanggroe Aceh Darussalam'),
    ('3210', 'Kab. Aceh Jeumpa/Bireuen', 'Nanggroe Aceh Darussalam'),
    ('3211', 'Kab. Aceh Tamiang', 'Nanggroe Aceh Darussalam'),
    ('3212', 'Kab. Gayo Luwes', 'Nanggroe Aceh Darussalam'),
    ('3213', 'Kab. Aceh Barat Daya', 'Nanggroe Aceh Darussalam'),
    ('3214', 'Kab. Aceh Jaya', 'Nanggroe Aceh Darussalam'),
    ('3215', 'Kab. Nagan Raya', 'Nanggroe Aceh Darussalam'),
    ('3216', 'Kab. Simeuleu', 'Nanggroe Aceh Darussalam'),
    ('3217', 'Kab. Bener Meriah', 'Nanggroe Aceh Darussalam'),
    ('3218', 'Kab. Pidie Jaya', 'Nanggroe Aceh Darussalam'),
    ('3219', 'Kab. Subulussalam', 'Nanggroe Aceh Darussalam'),
    ('3291', 'Kota Banda Aceh', 'Nanggroe Aceh Darussalam'),
    ('3292', 'Kota Sabang', 'Nanggroe Aceh Darussalam'),
    ('3293', 'Kota Lhokseumawe', 'Nanggroe Aceh Darussalam'),
    ('3294', 'Kota Langsa', 'Nanggroe Aceh Darussalam'),
    ('3301', 'Kab. Deli Serdang', 'Sumatera Utara'),
    ('3302', 'Kab. Langkat', 'Sumatera Utara'),
    ('3303', 'Kab. Karo', 'Sumatera Utara'),
    ('3304', 'Kab. Simalungun', 'Sumatera Utara'),
    ('3305', 'Kab. Labuhan Batu', 'Sumatera Utara'),
    ('3306', 'Kab. Asahan', 'Sumatera Utara'),
    ('3307', 'Kab. Dairi', 'Sumatera Utara'),
    ('3308', 'Kab. Tapanuli Utara', 'Sumatera Utara'),
    ('3309', 'Kab. Tapanuli Tengah', 'Sumatera Utara'),
    ('3310', 'Kab. Tapanuli Selatan', 'Sumatera Utara'),
    ('3311', 'Kab. Nias', 'Sumatera Utara'),
    ('3313', 'Kab. Toba Samosir', 'Sumatera Utara'),
    ('3314', 'Kab. Mandailing Natal', 'Sumatera Utara'),
    ('3315', 'Kab. Nias Selatan', 'Sumatera Utara'),
    ('3316', 'Kab. Humbang Hasundutan', 'Sumatera Utara'),
    ('3317', 'Kab. Pakpak Bharat', 'Sumatera Utara'),
    ('3318', 'Kab. Samosir', 'Sumatera Utara'),
    ('3319', 'Kab. Serdang Bedagai', 'Sumatera Utara'),
    ('3321', 'Kab. Batu Bara', 'Sumatera Utara'),
    ('3322', 'Kab. Padang Lawas', 'Sumatera Utara'),
    ('3323', 'Kab. Padang Lawas Utara', 'Sumatera Utara'),
    ('3324', 'Kab. Labuanbatu Selatan', 'Sumatera Utara'),
    ('3325', 'Kab. Labuanbatu Utara', 'Sumatera Utara'),
    ('3326', 'Kab. Nias Barat', 'Sumatera Utara'),
    ('3327', 'Kab. Nias Utara', 'Sumatera Utara'),
    ('3391', 'Kota Tebing Tinggi', 'Sumatera Utara'),
    ('3392', 'Kota Binjai', 'Sumatera Utara'),
    ('3393', 'Kota Pematang Siantar', 'Sumatera Utara'),
    ('3394', 'Kota Tanjung Balai', 'Sumatera Utara'),
    ('3395', 'Kota Sibolga', 'Sumatera Utara'),
    ('3396', 'Kota Medan', 'Sumatera Utara'),
    ('3397', 'Kota Gunung Sitoli', 'Sumatera Utara'),
    ('3399', 'Kota Padang Sidempuan', 'Sumatera Utara'),
    ('3401', 'Kab. Agam', 'Sumatera Barat'),
    ('3402', 'Kab. Pasaman', 'Sumatera Barat'),
    ('3403', 'Kab. Limapuluh Kota', 'Sumatera Barat'),
    ('3404', 'Kab. Solok Selatan', 'Sumatera Barat'),
    ('3405', 'Kab. Padang Pariaman', 'Sumatera Barat'),
    ('3406', 'Kab. Pesisir Selatan', 'Sumatera Barat'),
    ('3407', 'Kab. Tanah Datar', 'Sumatera Barat'),
    ('3408', 'Kab. Sawah Lunto/Sijunjung', 'Sumatera Barat'),
    ('3409', 'Kab. Kepulauan Mentawai', 'Sumatera Barat'),
    ('3410', 'Kab. Pasaman Barat', 'Sumatera Barat'),
    ('3411', 'Kab. Dharmasraya', 'Sumatera Barat'),
    ('3412', 'Kab. Solok', 'Sumatera Barat'),
    ('3491', 'Kota Bukittinggi', 'Sumatera Barat'),
    ('3492', 'Kota Padang', 'Sumatera Barat'),
    ('3493', 'Kota Sawahlunto', 'Sumatera Barat'),
    ('3494', 'Kota Padang Panjang', 'Sumatera Barat'),
    ('3495', 'Kota Solok', 'Sumatera Barat'),
    ('3496', 'Kota Payakumbuh', 'Sumatera Barat'),
    ('3497', 'Kota Pariaman', 'Sumatera Barat'),
    ('3501', 'Kab. Kampar', 'Riau'),
    ('3502', 'Kab. Bengkalis', 'Riau'),
    ('3504', 'Kab. Indragiri Hulu', 'Riau'),
    ('3505', 'Kab. Indragiri Hilir', 'Riau'),
    ('3508', 'Kab. Rokan Hulu', 'Riau'),
    ('3509', 'Kab. Rokan Hilir', 'Riau'),
    ('3510', 'Kab. Pelalawan', 'Riau'),
    ('3511', 'Kab. Siak', 'Riau'),
    ('3512', 'Kab. Kuantan Singingi', 'Riau'),
    ('3513', 'Kab. Kepulauan Meranti', 'Riau'),
    ('3591', 'Kota Pekanbaru', 'Riau'),
    ('3592', 'Kota Dumai', 'Riau'),
    ('3606', 'Kab. Musi Banyuasin', 'Sumatera Selatan'),
    ('3607', 'Kab. Ogan Komering Ulu', 'Sumatera Selatan'),
    ('3608', 'Kab. Lematang Ilir Ogan Tengah (Muara Enim)', 'Sumatera Selatan'),
    ('3609', 'Kab. Lahat', 'Sumatera Selatan'),
    ('3610', 'Kab. Musi Rawas', 'Sumatera Selatan'),
    ('3611', 'Kab. Ogan Komering Ilir', 'Sumatera Selatan'),
    ('3613', 'Kab. Banyuasin', 'Sumatera Selatan'),
    ('3614', 'Kab. Ogan Komering Ulu Selatan', 'Sumatera Selatan'),
    ('3615', 'Kab. Ogan Komering Ulu Timur', 'Sumatera Selatan'),
    ('3616', 'Kab. Ogan Ilir', 'Sumatera Selatan'),
    ('3617', 'Kab. Empat Lawang', 'Sumatera Selatan'),
    ('3618', 'Kab. Musi Rawas Utara', 'Sumatera Selatan'),
    ('3619', 'Kab. Penukal Abab Lematang Ilir', 'Sumatera Selatan'),
    ('3691', 'Kota Palembang', 'Sumatera Selatan'),
    ('3693', 'Kota Lubuklinggau', 'Sumatera Selatan'),
    ('3694', 'Kota Prabumulih', 'Sumatera Selatan'),
    ('3697', 'Kota Pagar Alam', 'Sumatera Selatan'),
    ('3701', 'Kab. Bangka', 'Kepulauan Bangka Belitung'),
    ('3702', 'Kab. Belitung', 'Kepulauan Bangka Belitung'),
    ('3703', 'Kab. Bangka Barat', 'Kepulauan Bangka Belitung'),
    ('3704', 'Kab. Bangka Selatan', 'Kepulauan Bangka Belitung'),
    ('3705', 'Kab. Bangka Tengah', 'Kepulauan Bangka Belitung'),
    ('3706', 'Kab. Belitung Timur', 'Kepulauan Bangka Belitung'),
    ('3707', 'Kota Pangkal Pinang', 'Kepulauan Bangka Belitung'),
    ('3801', 'Kab. Karimun', 'Kepulauan Riau'),
    ('3802', 'Kab. Lingga', 'Kepulauan Riau'),
    ('3803', 'Kab. Natuna', 'Kepulauan Riau'),
    ('3804', 'Kab. Bintan (d/h Kabupaten Kepulauan Riau)', 'Kepulauan Riau'),
    ('3805', 'Kab. Kepulauan Anambas', 'Kepulauan Riau'),
    ('3891', 'Kota Tanjung Pinang', 'Kepulauan Riau'),
    ('3892', 'Kota Batam', 'Kepulauan Riau'),
    ('3901', 'Kab. Lampung Selatan', 'Lampung'),
    ('3902', 'Kab. Lampung Tengah', 'Lampung'),
    ('3903', 'Kab. Lampung Utara', 'Lampung'),
    ('3904', 'Kab. Lampung Barat', 'Lampung'),
    ('3905', 'Kab. Tulang Bawang', 'Lampung'),
    ('3906', 'Kab. Tanggamus', 'Lampung'),
    ('3907', 'Kab. Lampung Timur', 'Lampung'),
    ('3908', 'Kab. Way Kanan', 'Lampung'),
    ('3909', 'Kab. Pesawaran', 'Lampung'),
    ('3910', 'Kab. Pringsewu', 'Lampung'),
    ('3911', 'Kab. Tulang Bawang Barat', 'Lampung'),
    ('3912', 'Kab. Mesuji', 'Lampung'),
    ('3913', 'Kab. Pesisir Barat', 'Lampung'),
    ('3991', 'Kota Bandar Lampung', 'Lampung'),
    ('3992', 'Kota Metro', 'Lampung'),
    ('5101', 'Kab. Banjar', 'Kalimantan Selatan'),
    ('5102', 'Kab. Tanah Laut', 'Kalimantan Selatan'),
    ('5103', 'Kab. Tapin', 'Kalimantan Selatan'),
    ('5104', 'Kab. Hulu Sungai Selatan', 'Kalimantan Selatan'),
    ('5105', 'Kab. Hulu Sungai Tengah', 'Kalimantan Selatan'),
    ('5106', 'Kab. Hulu Sungai Utara', 'Kalimantan Selatan'),
    ('5107', 'Kab. Barito Kuala', 'Kalimantan Selatan'),
    ('5108', 'Kab. Kota Baru', 'Kalimantan Selatan'),
    ('5109', 'Kab. Tabalong', 'Kalimantan Selatan'),
    ('5110', 'Kab. Tanah Bumbu', 'Kalimantan Selatan'),
    ('5111', 'Kab. Balangan', 'Kalimantan Selatan'),
    ('5191', 'Kota Banjarmasin', 'Kalimantan Selatan'),
    ('5192', 'Kota Banjarbaru', 'Kalimantan Selatan'),
    ('5301', 'Kab. Pontianak', 'Kalimantan Barat'),
    ('5302', 'Kab. Sambas', 'Kalimantan Barat'),
    ('5303', 'Kab. Ketapang', 'Kalimantan Barat'),
    ('5304', 'Kab. Sanggau', 'Kalimantan Barat'),
    ('5305', 'Kab. Sintang', 'Kalimantan Barat'),
    ('5306', 'Kab. Kapuas Hulu', 'Kalimantan Barat'),
    ('5307', 'Kab. Bengkayang', 'Kalimantan Barat'),
    ('5308', 'Kab. Landak', 'Kalimantan Barat'),
    ('5309', 'Kab. Sekadau', 'Kalimantan Barat'),
    ('5310', 'Kab. Melawi', 'Kalimantan Barat'),
    ('5311', 'Kab. Kayong Utara', 'Kalimantan Barat'),
    ('5312', 'Kab. Kubu Raya', 'Kalimantan Barat'),
    ('5391', 'Kota Pontianak', 'Kalimantan Barat'),
    ('5392', 'Kota Singkawang', 'Kalimantan Barat'),
    ('5401', 'Kab. Kutai Kartanegara', 'Kalimantan Timur'),
    ('5402', 'Kab. Berau', 'Kalimantan Timur'),
    ('5403', 'Kab. Paser', 'Kalimantan Timur'),
    ('5405', 'Kab. Kutai Barat', 'Kalimantan Timur'),
    ('5406', 'Kab. Kutai Timur', 'Kalimantan Timur'),
    ('5411', 'Kab. Penajam Paser Utara', 'Kalimantan Timur'),
    ('5413', 'Kab. Mahakam Ulu', 'Kalimantan Timur'),
    ('5491', 'Kota Samarinda', 'Kalimantan Timur'),
    ('5492', 'Kota Balikpapan', 'Kalimantan Timur'),
    ('5494', 'Kota Bontang', 'Kalimantan Timur'),
    ('5404', 'Kab. Bulungan', 'Kalimantan Utara'),
    ('5409', 'Kab. Nunukan', 'Kalimantan Utara'),
    ('5410', 'Kab. Malinau', 'Kalimantan Utara'),
    ('5412', 'Kab. Tana Tidung', 'Kalimantan Utara'),
    ('5493', 'Kota Tarakan', 'Kalimantan Utara'),
    ('5801', 'Kab. Kapuas', 'Kalimantan Tengah'),
    ('5802', 'Kab. Kotawaringin Barat', 'Kalimantan Tengah'),
    ('5803', 'Kab. Kotawaringin Timur', 'Kalimantan Tengah'),
    ('5804', 'Kab. Murung Raya', 'Kalimantan Tengah'),
    ('5805', 'Kab. Barito Timur', 'Kalimantan Tengah'),
    ('5806', 'Kab. Barito Selatan', 'Kalimantan Tengah'),
    ('5807', 'Kab. Gunung Mas', 'Kalimantan Tengah'),
    ('5808', 'Kab. Barito Utara', 'Kalimantan Tengah'),
    ('5809', 'Kab. Pulang Pisau', 'Kalimantan Tengah'),
    ('5810', 'Kab. Seruyan', 'Kalimantan Tengah'),
    ('5811', 'Kab. Katingan', 'Kalimantan Tengah'),
    ('5812', 'Kab. Sukamara', 'Kalimantan Tengah'),
    ('5813', 'Kab. Lamandau', 'Kalimantan Tengah'),
    ('5892', 'Kota Palangkaraya', 'Kalimantan Tengah'),
    ('6001', 'Kab. Donggala', 'Sulawesi Tengah'),
    ('6002', 'Kab. Poso', 'Sulawesi Tengah'),
    ('6003', 'Kab. Banggai', 'Sulawesi Tengah'),
    ('6004', 'Kab. Toli-Toli', 'Sulawesi Tengah'),
    ('6005', 'Kab. Banggai Kepulauan', 'Sulawesi Tengah'),
    ('6006', 'Kab. Morowali', 'Sulawesi Tengah'),
    ('6007', 'Kab. Buol', 'Sulawesi Tengah'),
    ('6008', 'Kab. Tojo Una-Una', 'Sulawesi Tengah'),
    ('6009', 'Kab. Parigi Moutong', 'Sulawesi Tengah'),
    ('6010', 'Kab. Sigi', 'Sulawesi Tengah'),
    ('6011', 'Kab. Banggai Laut', 'Sulawesi Tengah'),
    ('6012', 'Kab. Morowali Utara', 'Sulawesi Tengah'),
    ('6091', 'Kota Palu', 'Sulawesi Tengah'),
    ('6101', 'Kab. Pinrang', 'Sulawesi Selatan'),
    ('6102', 'Kab. Gowa', 'Sulawesi Selatan'),
    ('6103', 'Kab. Wajo', 'Sulawesi Selatan'),
    ('6105', 'Kab. Bone', 'Sulawesi Selatan'),
    ('6106', 'Kab. Tana Toraja', 'Sulawesi Selatan'),
    ('6107', 'Kab. Maros', 'Sulawesi Selatan'),
    ('6109', 'Kab. Luwu', 'Sulawesi Selatan'),
    ('6110', 'Kab. Sinjai', 'Sulawesi Selatan'),
    ('6111', 'Kab. Bulukumba', 'Sulawesi Selatan'),
    ('6112', 'Kab. Bantaeng', 'Sulawesi Selatan'),
    ('6113', 'Kab. Jeneponto', 'Sulawesi Selatan'),
    ('6114', 'Kab. Kepulauan Selayar', 'Sulawesi Selatan'),
    ('6115', 'Kab. Takalar', 'Sulawesi Selatan'),
    ('6116', 'Kab. Barru', 'Sulawesi Selatan'),
    ('6117', 'Kab. Sidenreng Rappang', 'Sulawesi Selatan'),
    ('6118', 'Kab. Pangkajene Kepulauan', 'Sulawesi Selatan'),
    ('6119', 'Kab. Soppeng (d/h Watansoppeng)', 'Sulawesi Selatan'),
    ('6121', 'Kab. Enrekang', 'Sulawesi Selatan'),
    ('6122', 'Kab. Luwu Timur (d/h Luwu Selatan)', 'Sulawesi Selatan'),
    ('6124', 'Kab. Luwu Utara', 'Sulawesi Selatan'),
    ('6125', 'Kab. Toraja Utara', 'Sulawesi Selatan'),
    ('6191', 'Kota Makassar', 'Sulawesi Selatan'),
    ('6192', 'Kota Pare-Pare', 'Sulawesi Selatan'),
    ('6193', 'Kota Palopo', 'Sulawesi Selatan'),
    ('6202', 'Kab. Minahasa', 'Sulawesi Utara'),
    ('6203', 'Kab. Bolaang Mongondow', 'Sulawesi Utara'),
    ('6204', 'Kab. Kepulauan Sangihe', 'Sulawesi Utara'),
    ('6205', 'Kab. Kepulauan Talaud', 'Sulawesi Utara'),
    ('6206', 'Kab. Minahasa Selatan', 'Sulawesi Utara'),
    ('6207', 'Kab. Minahasa Utara', 'Sulawesi Utara'),
    ('6209', 'Kab. Minahasa Tenggara', 'Sulawesi Utara'),
    ('6210', 'Kab. Bolaang Mongondow Utara', 'Sulawesi Utara'),
    ('6211', 'Kab. Kepulauan Sitaro', 'Sulawesi Utara'),
    ('6212', 'Kab. Bolaang Mongondow Selatan', 'Sulawesi Utara'),
    ('6213', 'Kab. Bolaang Mongondow Timur', 'Sulawesi Utara'),
    ('6291', 'Kota Manado', 'Sulawesi Utara'),
    ('6292', 'Kota Kotamobagu', 'Sulawesi Utara'),
    ('6293', 'Kota Bitung', 'Sulawesi Utara'),
    ('6294', 'Kota Tomohon', 'Sulawesi Utara'),
    ('6301', 'Kab. Gorontalo', 'Gorontalo'),
    ('6302', 'Kab. Bualemo', 'Gorontalo'),
    ('6303', 'Kab. Bonebolango', 'Gorontalo'),
    ('6304', 'Kab. Pohuwato', 'Gorontalo'),
    ('6305', 'Kab. Gorontalo Utara', 'Gorontalo'),
    ('6391', 'Kota Gorontalo', 'Gorontalo'),
    ('6401', 'Kab. Polewali Mandar', 'Sulawesi Barat'),
    ('6402', 'Kab. Majene', 'Sulawesi Barat'),
    ('6403', 'Kab. Mamasa', 'Sulawesi Barat'),
    ('6404', 'Kab. Mamuju Utara', 'Sulawesi Barat'),
    ('6405', 'Kab. Mamuju Tengah', 'Sulawesi Barat'),
    ('6406', 'Kab. Mamuju', 'Sulawesi Barat'),
    ('6901', 'Kab. Buton', 'Sulawesi Tenggara'),
    ('6903', 'Kab. Muna', 'Sulawesi Tenggara'),
    ('6904', 'Kab. Kolaka', 'Sulawesi Tenggara'),
    ('6905', 'Kab. Wakatobi', 'Sulawesi Tenggara'),
    ('6906', 'Kab. Konawe', 'Sulawesi Tenggara'),
    ('6907', 'Kab. Konawe Selatan', 'Sulawesi Tenggara'),
    ('6908', 'Kab. Bombana', 'Sulawesi Tenggara'),
    ('6909', 'Kab. Kolaka Utara', 'Sulawesi Tenggara'),
    ('6910', 'Kab. Buton Utara', 'Sulawesi Tenggara'),
    ('6911', 'Kab. Konawe Utara', 'Sulawesi Tenggara'),
    ('6912', 'Kab. Kaloka Timur', 'Sulawesi Tenggara'),
    ('6913', 'Kab. Konawe Kepulauan', 'Sulawesi Tenggara'),
    ('6914', 'Kab. Buton Selatan', 'Sulawesi Tenggara'),
    ('6915', 'Kab. Buton Tengah', 'Sulawesi Tenggara'),
    ('6916', 'Kab. Muna Barat', 'Sulawesi Tenggara'),
    ('6990', 'Kota Bau-Bau', 'Sulawesi Tenggara'),
    ('6991', 'Kota Kendari', 'Sulawesi Tenggara'),
    ('7101', 'Kab. Lombok Barat', 'Nusa Tenggara Barat'),
    ('7102', 'Kab. Lombok Tengah', 'Nusa Tenggara Barat'),
    ('7103', 'Kab. Lombok Timur', 'Nusa Tenggara Barat'),
    ('7104', 'Kab. Sumbawa', 'Nusa Tenggara Barat'),
    ('7105', 'Kab. Bima', 'Nusa Tenggara Barat'),
    ('7106', 'Kab. Dompu', 'Nusa Tenggara Barat'),
    ('7107', 'Kab. Sumbawa Barat', 'Nusa Tenggara Barat'),
    ('7108', 'Kab. Lombok Utara', 'Nusa Tenggara Barat'),
    ('7191', 'Kota Mataram', 'Nusa Tenggara Barat'),
    ('7192', 'Kota Bima', 'Nusa Tenggara Barat'),
    ('7201', 'Kab. Buleleng', 'Bali'),
    ('7202', 'Kab. Jembrana', 'Bali'),
    ('7203', 'Kab. Tabanan', 'Bali'),
    ('7204', 'Kab. Badung', 'Bali'),
    ('7205', 'Kab. Gianyar', 'Bali'),
    ('7206', 'Kab. Klungkung', 'Bali'),
    ('7207', 'Kab. Bangli', 'Bali'),
    ('7208', 'Kab. Karangasem', 'Bali'),
    ('7291', 'Kota Denpasar', 'Bali'),
    ('7401', 'Kab. Kupang', 'Nusa Tenggara Timur'),
    ('7402', 'Kab. Timor-Tengah Selatan', 'Nusa Tenggara Timur'),
    ('7403', 'Kab. Timor-Tengah Utara', 'Nusa Tenggara Timur'),
    ('7404', 'Kab. Belu', 'Nusa Tenggara Timur'),
    ('7405', 'Kab. Alor', 'Nusa Tenggara Timur'),
    ('7406', 'Kab. Flores Timur', 'Nusa Tenggara Timur'),
    ('7407', 'Kab. Sikka', 'Nusa Tenggara Timur'),
    ('7408', 'Kab. Ende', 'Nusa Tenggara Timur'),
    ('7409', 'Kab. Ngada', 'Nusa Tenggara Timur'),
    ('7410', 'Kab. Manggarai', 'Nusa Tenggara Timur'),
    ('7411', 'Kab. Sumba Timur', 'Nusa Tenggara Timur'),
    ('7412', 'Kab. Sumba Barat', 'Nusa Tenggara Timur'),
    ('7413', 'Kab. Lembata', 'Nusa Tenggara Timur'),
    ('7414', 'Kab. Rote Ndao', 'Nusa Tenggara Timur'),
    ('7415', 'Kab. Manggarai Barat', 'Nusa Tenggara Timur'),
    ('7416', 'Kab. Sumba Tengah', 'Nusa Tenggara Timur'),
    ('7417', 'Kab. Sumba Barat Daya', 'Nusa Tenggara Timur'),
    ('7418', 'Kab. Manggarai Timur', 'Nusa Tenggara Timur'),
    ('7419', 'Kab. Nagekeo', 'Nusa Tenggara Timur'),
    ('7420', 'Kab. Sabu Raijua', 'Nusa Tenggara Timur'),
    ('7421', 'Kab. Malaka', 'Nusa Tenggara Timur'),
    ('7491', 'Kota Kupang', 'Nusa Tenggara Timur'),
    ('8101', 'Kab. Maluku Tengah', 'Maluku'),
    ('8102', 'Kab. Maluku Tenggara', 'Maluku'),
    ('8103', 'Kab. Maluku Tenggara Barat', 'Maluku'),
    ('8104', 'Kab. Buru', 'Maluku'),
    ('8105', 'Kab. Seram Bagian Barat', 'Maluku'),
    ('8106', 'Kab. Seram Bagian Timur', 'Maluku'),
    ('8107', 'Kab. Kepulauan Aru', 'Maluku'),
    ('8108', 'Kab. Maluku Barat Daya', 'Maluku'),
    ('8109', 'Kab. Buru Selatan', 'Maluku'),
    ('8191', 'Kota Ambon', 'Maluku'),
    ('8192', 'Kota Tual', 'Maluku'),
    ('8201', 'Kab. Jayapura', 'Papua'),
    ('8202', 'Kab. Biak Numfor', 'Papua'),
    ('8210', 'Kab. Kepulauan Yapen-Waropen', 'Papua'),
    ('8211', 'Kab. Merauke', 'Papua'),
    ('8212', 'Kab. Paniai', 'Papua'),
    ('8213', 'Kab. Jayawijaya', 'Papua'),
    ('8214', 'Kab. Nabire', 'Papua'),
    ('8215', 'Kab. Mimika', 'Papua'),
    ('8216', 'Kab. Puncak Jaya', 'Papua'),
    ('8217', 'Kab. Sarmi', 'Papua'),
    ('8218', 'Kab. Keerom', 'Papua'),
    ('8221', 'Kab. Pegunungan Bintang', 'Papua'),
    ('8222', 'Kab. Yahukimo', 'Papua'),
    ('8223', 'Kab. Tolikara', 'Papua'),
    ('8224', 'Kab. Waropen', 'Papua'),
    ('8226', 'Kab. Boven Digoel', 'Papua'),
    ('8227', 'Kab. Mappi', 'Papua'),
    ('8228', 'Kab. Asmat', 'Papua'),
    ('8231', 'Kab. Supiori', 'Papua'),
    ('8232', 'Kab. Mamberamo Raya', 'Papua'),
    ('8233', 'Kab. Dogiyai', 'Papua'),
    ('8234', 'Kab. Lanny Jaya', 'Papua'),
    ('8235', 'Kab. Mamberamo Tengah', 'Papua'),
    ('8236', 'Kab. Nduga', 'Papua'),
    ('8237', 'Kab. Yalimo', 'Papua'),
    ('8238', 'Kab. Puncak', 'Papua'),
    ('8239', 'Kab. Intan Jaya', 'Papua'),
    ('8240', 'Kab. Deiya', 'Papua'),
    ('8291', 'Kota Jayapura', 'Papua'),
    ('8302', 'Kab. Halmahera Tengah', 'Maluku Utara'),
    ('8303', 'Kab. Halmahera Utara', 'Maluku Utara'),
    ('8304', 'Kab. Halmahera Timur', 'Maluku Utara'),
    ('8305', 'Kab. Halmahera Barat', 'Maluku Utara'),
    ('8306', 'Kab. Halmahera Selatan', 'Maluku Utara'),
    ('8307', 'Kab. Kepulauan Sula', 'Maluku Utara'),
    ('8308', 'Kab. Pulau Morotai', 'Maluku Utara'),
    ('8309', 'Kab. Pulau Taliabu', 'Maluku Utara'),
    ('8390', 'Kota Ternate', 'Maluku Utara'),
    ('8391', 'Kota Tidore Kepulauan', 'Maluku Utara'),
    ('8401', 'Kab. Sorong', 'Papua Barat'),
    ('8402', 'Kab. Fak-Fak', 'Papua Barat'),
    ('8403', 'Kab. Manokwari', 'Papua Barat'),
    ('8404', 'Kab. Sorong Selatan', 'Papua Barat'),
    ('8405', 'Kab. Raja Ampat', 'Papua Barat'),
    ('8406', 'Kab. Kaimana', 'Papua Barat'),
    ('8407', 'Kab. Teluk Bintuni', 'Papua Barat'),
    ('8408', 'Kab. Teluk Wondama', 'Papua Barat'),
    ('8409', 'Kab. Tembrauw', 'Papua Barat'),
    ('8410', 'Kab. Maybrat', 'Papua Barat'),
    ('8411', 'Kab. Pegunungan Arfak', 'Papua Barat'),
    ('8412', 'Kab. Manokwari Selatan', 'Papua Barat'),
    ('8491', 'Kota Sorong', 'Papua Barat')
ON CONFLICT (code) DO NOTHING;

-- Lampiran 05 - Sektor Ekonomi (476 baris)
INSERT INTO ojk_sektor_ekonomi (code, label) VALUES
    ('A00000', 'PERTANIAN, KEHUTANAN DAN PERIKANAN'),
    ('011110', 'PERTANIAN JAGUNG'),
    ('011130', 'PERTANIAN KEDELAI'),
    ('011140', 'PERTANIAN KACANG TANAH'),
    ('011190', 'PERTANIAN SEREALIA LAINNYA, ANEKA KACANG DAN BIJI-BIJIAN PENGHASIL MINYAK LAINNYA'),
    ('011200', 'PERTANIAN PADI'),
    ('011301', 'PERTANIAN HORTIKULTURA BAWANG MERAH'),
    ('011302', 'PERTANIAN ANEKA UMBI PALAWIJA'),
    ('011303', 'PERTANIAN BIT GULA DAN TANAMAN PEMANIS BUKAN TEBU'),
    ('011309', 'PERTANIAN SAYURAN, BUAH DAN ANEKA UMBI LAINNYA'),
    ('011400', 'PERKEBUNAN TEBU'),
    ('011500', 'PERKEBUNAN TEMBAKAU'),
    ('011600', 'PERTANIAN TANAMAN BERSERAT'),
    ('011930', 'PERTANIAN TANAMAN BUNGA'),
    ('011940', 'PERTANIAN PEMBIBITAN TANAMAN BUNGA'),
    ('011909', 'PERTANIAN TANAMAN SEMUSIM LAINNYA YTDL'),
    ('012201', 'PERTANIAN BUAH PISANG'),
    ('012209', 'PERTANIAN BUAH-BUAHAN TROPIS DAN SUBTROPIS LAINNYA'),
    ('012300', 'PERTANIAN BUAH JERUK'),
    ('012400', 'PERTANIAN BUAH APEL DAN BUAH BATU (POME AND STONE FRUITS)'),
    ('012500', 'PERTANIAN SAYURAN DAN BUAH SEMAK DAN BUAH BIJI KACANG-KACANGAN LAINNYA'),
    ('012610', 'PERKEBUNAN BUAH KELAPA'),
    ('012620', 'PERKEBUNAN BUAH KELAPA SAWIT'),
    ('012690', 'PERKEBUNAN BUAH OLEAGINOUS LAINNYA'),
    ('012701', 'PERKEBUNAN TANAMAN KOPI'),
    ('012702', 'PERKEBUNAN TANAMAN TEH'),
    ('012703', 'PERKEBUNAN TANAMAN COKLAT (KAKAO)'),
    ('012709', 'PERTANIAN TANAMAN UNTUK BAHAN MINUMAN LAINNYA'),
    ('012810', 'PERKEBUNAN LADA'),
    ('012820', 'PERKEBUNAN CENGKEH'),
    ('012830', 'PERTANIAN CABAI'),
    ('012840', 'PERKEBUNAN TANAMAN AROMATIK/PENYEGAR'),
    ('012850', 'PERKEBUNAN TANAMAN OBAT / BAHAN FARMASI'),
    ('012891', 'PERKEBUNAN TANAMAN REMPAH VANILI'),
    ('012892', 'PERKEBUNAN TANAMAN REMPAH PALA'),
    ('012899', 'PERKEBUNAN TANAMAN REMPAH YANG TIDAK DIKLASIFIKASIKAN DI TEMPAT LAIN'),
    ('012910', 'PERKEBUNAN KARET DAN TANAMAN PENGHASIL GETAH LAINNYA'),
    ('012990', 'PERTANIAN CEMARA DAN TANAMAN TAHUNAN LAINNYA'),
    ('013010', 'PERTANIAN TANAMAN HIAS'),
    ('013020', 'PERTANIAN PENGEMBANGBIAKAN TANAMAN'),
    ('014110', 'PEMBIBITAN DAN BUDIDAYA SAPI POTONG'),
    ('014120', 'PEMBIBITAN DAN BUDIDAYA SAPI PERAH'),
    ('014130', 'PEMBIBITAN DAN BUDIDAYA KERBAU POTONG'),
    ('014140', 'PEMBIBITAN DAN BUDIDAYA KERBAU PERAH'),
    ('014400', 'PETERNAKAN DOMBA DAN KAMBING'),
    ('014500', 'PETERNAKAN BABI'),
    ('014600', 'PETERNAKAN UNGGAS'),
    ('014900', 'PETERNAKAN LAINNYA'),
    ('016000', 'JASA PENUNJANG PERTANIAN DAN PASCA PANEN'),
    ('017000', 'PERBURUAN, PENANGKAPAN DAN PENANGKARAN TUMBUHAN/ SATWA LIAR'),
    ('021100', 'PENGUSAHAAN HUTAN TANAMAN'),
    ('021200', 'PENGUSAHAAN HUTAN ALAM'),
    ('021300', 'PENGUSAHAAN HASIL HUTAN BUKAN KAYU'),
    ('021400', 'PENGUSAHAAN PEMBIBITAN TANAMAN KEHUTANAN'),
    ('022090', 'USAHA KEHUTANAN LAINNYA'),
    ('024000', 'JASA PENUNJANG KEHUTANAN'),
    ('031111', 'PENANGKAPAN IKAN TUNA'),
    ('031119', 'PENANGKAPAN IKAN LAINNYA'),
    ('031121', 'PENANGKAPAN UDANG LAUT'),
    ('031129', 'PENANGKAPAN CRUSTACEA LAINNYA DI LAUT'),
    ('031190', 'PENANGKAPAN BIOTA AIR LAINNYA DI LAUT'),
    ('031210', 'PENANGKAPAN PISCES/IKAN BERSIRIP DI PERAIRAN UMUM'),
    ('031290', 'PENANGKAPAN BIOTA AIR LAINNYA DI PERAIRAN UMUM'),
    ('031300', 'JASA PENANGKAPAN IKAN DI LAUT'),
    ('031400', 'JASA PENANGKAPAN IKAN DI PERAIRAN UMUM'),
    ('032101', 'BUDIDAYA BIOTA LAUT UDANG'),
    ('032102', 'BUDIDAYA BIOTA LAUT RUMPUT LAUT'),
    ('032109', 'BUDIDAYA BIOTA LAUT LAINNYA'),
    ('032201', 'BUDIDAYA BIOTA AIR TAWAR UDANG'),
    ('032202', 'PEMBENIHAN IKAN AIR TAWAR'),
    ('032209', 'BUDIDAYA BIOTA AIR TAWAR LAINNYA'),
    ('032300', 'JASA BUDIDAYA IKAN LAUT'),
    ('032400', 'JASA BUDIDAYA IKAN AIR TAWAR'),
    ('032501', 'BUDIDAYA BIOTA AIR PAYAU UDANG'),
    ('032509', 'BUDIDAYA BIOTA AIR PAYAU LAINNYA'),
    ('032600', 'JASA BUDIDAYA IKAN AIR PAYAU'),
    ('B00000', 'PERTAMBANGAN DAN PENGGALIAN'),
    ('050000', 'PERTAMBANGAN BATU BARA DAN LIGNIT'),
    ('060001', 'PERTAMBANGAN MINYAK BUMI DAN GAS ALAM'),
    ('060002', 'PENGUSAHAAN TENAGA PANAS BUMI'),
    ('071000', 'PERTAMBANGAN PASIR BESI DAN BIJIH BESI'),
    ('072100', 'PERTAMBANGAN BIJIH URANIUM DAN TORIUM'),
    ('072910', 'PERTAMBANGAN BIJIH TIMAH'),
    ('072930', 'PERTAMBANGAN BIJIH BAUKSIT/ALUMINIUM'),
    ('072940', 'PERTAMBANGAN BIJIH TEMBAGA'),
    ('072950', 'PERTAMBANGAN BIJIH NIKEL'),
    ('072990', 'PERTAMBANGAN BAHAN GALIAN LAINNYA YANG TIDAK MENGANDUNG BIJIH BESI'),
    ('073011', 'PERTAMBANGAN EMAS'),
    ('073012', 'PERTAMBANGAN PERAK'),
    ('073090', 'PERTAMBANGAN BIJIH LOGAM MULIA LAINNYA'),
    ('081000', 'PENGGALIAN BATU, PASIR DAN TANAH LIAT'),
    ('089100', 'PERTAMBANGAN MINERAL, BAHAN KIMIA DAN BAHAN PUPUK'),
    ('089300', 'EKSTRAKSI GARAM'),
    ('089900', 'PERTAMBANGAN DAN PENGGALIAN LAINNYA YTDL'),
    ('091000', 'AKTIVITAS PENUNJANG PERTAMBANGAN MINYAK BUMI DAN GAS ALAM'),
    ('099000', 'AKTIVITAS PENUNJANG PERTAMBANGAN DAN PENGGALIAN LAINNYA'),
    ('C00000', 'INDUSTRI PENGOLAHAN'),
    ('101000', 'INDUSTRI PENGOLAHAN DAN PENGAWETAN DAGING'),
    ('102000', 'INDUSTRI PENGOLAHAN DAN PENGAWETAN IKAN DAN BIOTA AIR'),
    ('103001', 'INDUSTRI TEMPE DAN TAHU KEDELAI'),
    ('103009', 'INDUSTRI PENGOLAHAN DAN PENGAWETAN LAINNYA BUAH-BUAHAN DAN SAYURAN'),
    ('104100', 'INDUSTRI MINYAK DAN LEMAK NABATI DAN HEWANI'),
    ('104210', 'INDUSTRI KOPRA, TEPUNG DAN PELET KELAPA'),
    ('104230', 'INDUSTRI MINYAK MENTAH KELAPA DAN MINYAK GORENG KELAPA'),
    ('104300', 'INDUSTRI MINYAK MENTAH/MURNI KELAPA SAWIT (CRUDE PALM OIL) DAN MINYAK GORENG KELAPA SAWIT'),
    ('104900', 'INDUSTRI MINYAK MENTAH DAN LEMAK NABATI DAN HEWANI LAINNYA'),
    ('105000', 'INDUSTRI PENGOLAHAN SUSU, PRODUK DARI SUSU DAN ES KRIM'),
    ('106100', 'INDUSTRI PENGGILINGAN SERELIA DAN BIJI-BIJIAN LAINNYA (BUKAN BERAS DAN JAGUNG)'),
    ('106200', 'INDUSTRI PATI DAN PRODUK PATI (BUKAN BERAS DAN JAGUNG)'),
    ('106300', 'INDUSTRI PENGGILINGAN BERAS DAN JAGUNG DAN INDUSTRI TEPUNG BERAS DAN JAGUNG'),
    ('107100', 'INDUSTRI PRODUK ROTI DAN KUE'),
    ('107200', 'INDUSTRI GULA'),
    ('107300', 'INDUSTRI KAKAO, COKELAT DAN KEMBANG GULA'),
    ('107400', 'INDUSTRI MAKARONI, MIE DAN PRODUK SEJENISNYA'),
    ('107610', 'INDUSTRI PENGOLAHAN KOPI'),
    ('107630', 'INDUSTRI PENGOLAHAN TEH'),
    ('107710', 'INDUSTRI KECAP'),
    ('107900', 'INDUSTRI PRODUK MAKANAN LAINNYA'),
    ('108000', 'INDUSTRI MAKANAN HEWAN'),
    ('110000', 'INDUSTRI MINUMAN'),
    ('120100', 'INDUSTRI ROKOK DAN PRODUK TEMBAKAU LAINNYA'),
    ('120900', 'INDUSTRI PENGOLAHAN TEMBAKAU LAINNYA'),
    ('131000', 'INDUSTRI PEMINTALAN, PENENUNAN DAN PENYELESAIAN AKHIR TEKSTIL'),
    ('139000', 'INDUSTRI TEKSTIL LAINNYA'),
    ('141000', 'INDUSTRI PAKAIAN JADI DAN PERLENGKAPANNYA, BUKAN PAKAIAN JADI DARI KULIT BERBULU'),
    ('142000', 'INDUSTRI PAKAIAN JADI DAN BARANG DARI KULIT BERBULU'),
    ('143000', 'INDUSTRI PAKAIAN JADI RAJUTAN DAN SULAMAN/BORDIR'),
    ('151000', 'INDUSTRI KULIT DAN BARANG DARI KULIT, TERMASUK KULIT BUATAN'),
    ('152000', 'INDUSTRI ALAS KAKI'),
    ('161000', 'INDUSTRI PENGGERGAJIAN DAN PENGAWETAN KAYU, ROTAN, BAMBU DAN SEJENISNYA'),
    ('162100', 'INDUSTRI KAYU LAPIS, VENEER DAN SEJENISNYA'),
    ('162900', 'INDUSTRI BARANG LAINNYA DARI KAYU; INDUSTRI BARANG DARI GABUS DAN BARANG ANYAMAN DARI JERAMI, ROTAN, BAMBU DAN SEJENISNYA'),
    ('170100', 'INDUSTRI BUBUR KERTAS, KERTAS DAN PAPAN KERTAS'),
    ('170200', 'INDUSTRI KERTAS DAN PAPAN KERTAS BERGELOMBANG DAN WADAH DARI KERTAS DAN PAPAN KERTAS'),
    ('170900', 'INDUSTRI BARANG DARI KERTAS DAN PAPAN KERTAS LAINNYA'),
    ('181000', 'INDUSTRI PENCETAKAN DAN KEGIATAN YBDI'),
    ('182000', 'REPRODUKSI MEDIA REKAMAN'),
    ('191000', 'INDUSTRI PRODUK DARI BATU BARA'),
    ('192100', 'INDUSTRI BAHAN BAKAR DAN MINYAK PELUMAS HASIL PENGILANGAN MINYAK BUMI'),
    ('192900', 'INDUSTRI BRIKET BATU BARA'),
    ('201100', 'INDUSTRI KIMIA DASAR'),
    ('201200', 'INDUSTRI PUPUK DAN BAHAN SENYAWA NITROGEN'),
    ('201300', 'INDUSTRI PLASTIK DAN KARET BUATAN DALAM BENTUK DASAR'),
    ('202100', 'INDUSTRI PESTISIDA DAN PRODUK AGROKIMIA LAINNYA'),
    ('202200', 'INDUSTRI CAT DAN TINTA CETAK, PERNIS DAN BAHAN PELAPISAN SEJENISNYA DAN LAK'),
    ('202300', 'INDUSTRI SABUN DAN DETERJEN, BAHAN PEMBERSIH DAN PENGILAP, PARFUM DAN KOSMETIK'),
    ('202940', 'INDUSTRI MINYAK ATSIRI'),
    ('202990', 'INDUSTRI BARANG KIMIA LAINNYA YTDL'),
    ('203000', 'INDUSTRI SERAT BUATAN'),
    ('210000', 'INDUSTRI FARMASI, PRODUK OBAT KIMIA DAN OBAT TRADISIONAL'),
    ('221210', 'INDUSTRI PENGASAPAN KARET'),
    ('221220', 'INDUSTRI REMILLING KARET'),
    ('221230', 'INDUSTRI KARET REMAH (CRUMB RUBBER)'),
    ('221900', 'INDUSTRI BARANG DARI KARET LAINNYA'),
    ('222000', 'INDUSTRI BARANG DARI PLASTIK'),
    ('231000', 'INDUSTRI KACA DAN BARANG DARI KACA'),
    ('239200', 'INDUSTRI BAHAN BANGUNAN DARI TANAH LIAT/KERAMIK'),
    ('239301', 'INDUSTRI BARANG PORSELEN BUKAN BAHAN BANGUNAN'),
    ('239302', 'INDUSTRI BARANG TANAH LIAT/KERAMIK BUKAN BAHAN BANGUNAN'),
    ('239400', 'INDUSTRI SEMEN, KAPUR DAN GIPS'),
    ('239600', 'INDUSTRI BARANG DARI BATU'),
    ('239900', 'INDUSTRI BARANG GALIAN BUKAN LOGAM LAINNYA YTDL'),
    ('241000', 'INDUSTRI LOGAM DASAR BESI DAN BAJA'),
    ('242060', 'INDUSTRI PENGOLAHAN URANIUM DAN BIJIH URANIUM'),
    ('242090', 'INDUSTRI LOGAM DASAR MULIA DAN LOGAM DASAR BUKAN BESI LAINNYA'),
    ('243100', 'INDUSTRI PENGECORAN BESI DAN BAJA'),
    ('243200', 'INDUSTRI PENGECORAN LOGAM BUKAN BESI DAN BAJA'),
    ('251000', 'INDUSTRI BARANG LOGAM SIAP PASANG UNTUK BANGUNAN, TANGKI, TANDON AIR DAN GENERATOR UAP'),
    ('259300', 'INDUSTRI ALAT POTONG, PERKAKAS TANGAN DAN PERALATAN UMUM'),
    ('259900', 'INDUSTRI BARANG LOGAM LAINNYA YTDL'),
    ('261000', 'INDUSTRI KOMPONEN DAN PAPAN ELEKTRONIK'),
    ('262000', 'INDUSTRI KOMPUTER DAN PERLENGKAPANNYA'),
    ('263000', 'INDUSTRI PERALATAN KOMUNIKASI'),
    ('264000', 'INDUSTRI PERALATAN AUDIO DAN VIDEO ELEKTRONIK'),
    ('265100', 'INDUSTRI ALAT UKUR, ALAT UJI, PERALATAN NAVIGASI DAN KONTROL'),
    ('265200', 'INDUSTRI ALAT UKUR WAKTU'),
    ('266000', 'INDUSTRI PERALATAN IRADIASI, ELEKTROMEDICAL DAN ELEKTROTERAPI'),
    ('267000', 'INDUSTRI PERALATAN FOTOGRAFI DAN INSTRUMEN OPTIK BUKAN KACA MATA'),
    ('269000', 'INDUSTRI KOMPUTER, BARANG ELEKTRONIK DAN OPTIK LAINNYA'),
    ('271100', 'INDUSTRI MOTOR LISTRIK, GENERATOR DAN TRANSFORMATOR'),
    ('271200', 'INDUSTRI PERALATAN PENGONTROL DAN PENDISTRIBUSIAN LISTRIK'),
    ('272000', 'INDUSTRI BATU BATERAI DAN AKUMULATOR LISTRIK'),
    ('273000', 'INDUSTRI KABEL DAN PERLENGKAPANNYA'),
    ('274000', 'INDUSTRI PERALATAN PENERANGAN LISTRIK (TERMASUK PERALATAN PENERANGAN BUKAN LISTRIK)'),
    ('275000', 'INDUSTRI PERALATAN RUMAH TANGGA'),
    ('279000', 'INDUSTRI PERALATAN LISTRIK LAINNYA'),
    ('281000', 'INDUSTRI MESIN UNTUK KEPERLUAN UMUM'),
    ('282100', 'INDUSTRI MESIN PERTANIAN DAN KEHUTANAN'),
    ('282400', 'INDUSTRI MESIN PENAMBANGAN, PENGGALIAN DAN KONSTRUKSI'),
    ('282500', 'INDUSTRI MESIN PENGOLAHAN MAKANAN, MINUMAN DAN TEMBAKAU'),
    ('282600', 'INDUSTRI MESIN TEKSTIL, PAKAIAN JADI DAN PRODUK KULIT'),
    ('282900', 'INDUSTRI MESIN KEPERLUAN KHUSUS LAINNYA'),
    ('291000', 'INDUSTRI KENDARAAN BERMOTOR RODA EMPAT ATAU LEBIH'),
    ('292000', 'INDUSTRI KAROSERI KENDARAAN BERMOTOR RODA EMPAT ATAU LEBIH DAN INDUSTRI TRAILER DAN SEMI TRAILER'),
    ('293000', 'INDUSTRI SUKU CADANG DAN AKSESORI KENDARAAN BERMOTOR RODA EMPAT ATAU LEBIH'),
    ('301000', 'INDUSTRI PEMBUATAN KAPAL DAN PERAHU'),
    ('302000', 'INDUSTRI LOKOMOTIF DAN GERBONG KERETA'),
    ('303000', 'INDUSTRI PESAWAT TERBANG DAN PERLENGKAPANNYA'),
    ('309110', 'INDUSTRI SEPEDA MOTOR RODA DUA DAN TIGA'),
    ('309900', 'INDUSTRI ALAT ANGKUTAN LAINNYA YTDL'),
    ('310000', 'INDUSTRI FURNITUR'),
    ('320000', 'INDUSTRI PENGOLAHAN LAINNYA'),
    ('330000', 'REPARASI DAN PEMASANGAN MESIN DAN PERALATAN'),
    ('D00000', 'PENGADAAN LISTRIK, GAS, UAP/AIR PANAS DAN UDARA DINGIN'),
    ('351001', 'KETENAGALISTRIKAN PEDESAAN'),
    ('351002', 'KETENAGALISTRIKAN LAINNYA'),
    ('352000', 'PENGADAAN DAN DISTRIBUSI GAS ALAM DAN BUATAN'),
    ('353000', 'PENGADAAN UAP/AIR PANAS, UDARA DINGIN DAN PRODUKSI ES'),
    ('E00000', 'PENGELOLAAN AIR, PENGELOLAAN AIR LIMBAH, PENGELOLAAN DAN DAUR ULANG SAMPAH, DAN AKTIVITAS REMEDIASI'),
    ('360000', 'PENGELOLAAN AIR'),
    ('370000', 'PENGELOLAAN AIR LIMBAH'),
    ('380000', 'PENGELOLAAN DAN DAUR ULANG SAMPAH'),
    ('390000', 'AKTIVITAS REMEDIASI DAN PENGELOLAAN SAMPAH LAINNYA'),
    ('F00000', 'KONSTRUKSI'),
    ('410111', 'KONSTRUKSI PERUMAHAN SEDERHANA BANK TABUNGAN NEGARA'),
    ('410112', 'KONSTRUKSI PERUMAHAN SEDERHANA PERUMNAS'),
    ('410113', 'KONSTRUKSI PERUMAHAN SEDERHANA LAINNYA TIPE S.D. 21'),
    ('410114', 'KONSTRUKSI PERUMAHAN SEDERHANA LAINNYA TIPE 22 S.D. 70'),
    ('410115', 'KONSTRUKSI PERUMAHAN MENENGAH, BESAR, MEWAH (TIPE DIATAS 70)'),
    ('410119', 'KONSTRUKSI GEDUNG TEMPAT TINGGAL LAINNYA'),
    ('410120', 'KONSTRUKSI GEDUNG PERKANTORAN'),
    ('410130', 'KONSTRUKSI GEDUNG INDUSTRI'),
    ('410141', 'KONSTRUKSI GEDUNG PERBELANJAAN PASAR INPRES'),
    ('410149', 'KONSTRUKSI GEDUNG PERBELANJAAN LAINNYA'),
    ('410190', 'KONSTRUKSI GEDUNG LAINNYA'),
    ('421101', 'KONSTRUKSI JALAN TOL'),
    ('421102', 'KONSTRUKSI JALAN RAYA SELAIN TOL'),
    ('421103', 'KONSTRUKSI JEMBATAN DAN JALAN LAYANG'),
    ('421104', 'KONSTRUKSI JALAN REL DAN JEMBATAN REL'),
    ('421109', 'KONSTRUKSI JALAN RAYA LAINNYA'),
    ('422110', 'KONSTRUKSI JARINGAN IRIGASI'),
    ('422131', 'KONSTRUKSI BANGUNAN LISTRIK PEDESAAN'),
    ('422139', 'KONSTRUKSI BANGUNAN ELEKTRIKAL DAN KOMUNIKASI LAINNYA'),
    ('422190', 'KONSTRUKSI JARINGAN ELEKTRIKAL DAN TELEKOMUNIKASI LAINNYA'),
    ('429120', 'KONSTRUKSI BANGUNAN PELABUHAN BUKAN PERIKANAN'),
    ('429190', 'KONSTRUKSI BANGUNAN SIPIL LAINNYA YTDL'),
    ('431201', 'PENYIAPAN TANAH PEMUKIMAN TRANSMIGRASI (PTPT)'),
    ('431202', 'PENCETAKAN LAHAN SAWAH'),
    ('431209', 'PENYIAPAN LAHAN LAINNYA DAN PEMBONGKARAN'),
    ('432000', 'INSTALASI SISTEM KELISTRIKAN, AIR (PIPA) DAN INSTALASI KONSTRUKSI LAINNYA'),
    ('433000', 'PENYELESAIAN KONSTRUKSI BANGUNAN'),
    ('439050', 'PENYEWAAN ALAT KONSTRUKSI DENGAN OPERATOR'),
    ('439090', 'KONSTRUKSI KHUSUS LAINNYA YTDL'),
    ('G00000', 'PERDAGANGAN BESAR DAN ECERAN; REPARASI DAN PERAWATAN MOBIL DAN SEPEDA MOTOR'),
    ('451000', 'PERDAGANGAN MOBIL'),
    ('452000', 'REPARASI DAN PERAWATAN MOBIL'),
    ('453000', 'PERDAGANGAN SUKU CADANG DAN AKSESORI MOBIL'),
    ('454001', 'PERDAGANGAN SEPEDA MOTOR'),
    ('454002', 'PERDAGANGAN SUKU CADANG SEPEDA MOTOR DAN AKSESORINYA'),
    ('454003', 'REPARASI DAN PERAWATAN SEPEDA MOTOR'),
    ('461000', 'PERDAGANGAN BESAR ATAS DASAR BALAS JASA (fee) ATAU KONTRAK'),
    ('462011', 'PERDAGANGAN BESAR JAGUNG'),
    ('462019', 'PERDAGANGAN BESAR PADI DAN PALAWIJA LAINNYA'),
    ('462020', 'PERDAGANGAN BESAR BUAH YANG MENGANDUNG MINYAK'),
    ('462040', 'PERDAGANGAN BESAR TEMBAKAU RAJANGAN'),
    ('462050', 'PERDAGANGAN BESAR BINATANG HIDUP'),
    ('462060', 'PERDAGANGAN BESAR HASIL PERIKANAN'),
    ('462071', 'PERDAGANGAN KAYU'),
    ('462079', 'PERDAGANGAN BESAR HASIL KEHUTANAN DAN PERBURUAN LAINNYA'),
    ('462080', 'PERDAGANGAN BESAR KULIT DAN KULIT JANGAT'),
    ('462091', 'PERDAGANGAN KARET'),
    ('462092', 'PERDAGANGAN CENGKEH'),
    ('462093', 'PERDAGANGAN LADA'),
    ('462094', 'PERDAGANGAN KAPAS'),
    ('462095', 'PERDAGANGAN BIJI KELAPA SAWIT'),
    ('462099', 'PERDAGANGAN BESAR HASIL PERTANIAN DAN HEWAN HIDUP LAINNYA'),
    ('463110', 'PERDAGANGAN BESAR BERAS'),
    ('463141', 'PERDAGANGAN BESAR KOPI'),
    ('463142', 'PERDAGANGAN BESAR TEH'),
    ('463150', 'PERDAGANGAN BESAR MINYAK DAN LEMAK NABATI'),
    ('463190', 'PERDAGANGAN BESAR BAHAN MAKANAN DAN MINUMAN HASIL PERTANIAN LAINNYA'),
    ('463201', 'PERDAGANGAN BESAR UDANG OLAHAN'),
    ('463209', 'PERDAGANGAN BESAR BAHAN MAKANAN DAN MINUMAN HASIL PETERNAKAN DAN PERIKANAN LAINNYA'),
    ('463301', 'PERDAGANGAN BESAR GULA, COKLAT DAN KEMBANG GULA'),
    ('463302', 'PERDAGANGAN BESAR ROKOK DAN TEMBAKAU'),
    ('463309', 'PERDAGANGAN BESAR MAKANAN DAN MINUMAN LAINNYA'),
    ('464110', 'PERDAGANGAN BESAR TEKSTIL'),
    ('464120', 'PERDAGANGAN BESAR PAKAIAN'),
    ('464130', 'PERDAGANGAN BESAR ALAS KAKI'),
    ('464190', 'PERDAGANGAN BESAR TEKSTIL, PAKAIAN DAN ALAS KAKI LAINNYA'),
    ('464900', 'PERDAGANGAN BESAR BARANG KEPERLUAN RUMAH TANGGA LAINNYA'),
    ('465000', 'PERDAGANGAN BESAR MESIN, PERALATAN DAN PERLENGKAPANNYA'),
    ('466100', 'PERDAGANGAN BESAR BAHAN BAKAR PADAT, CAIR DAN GAS DAN PRODUK YBDI'),
    ('466200', 'PERDAGANGAN BESAR LOGAM DAN BIJIH LOGAM'),
    ('466301', 'PERDAGANGAN BESAR BAHAN KONSTRUKSI DARI KAYU'),
    ('466309', 'PERDAGANGAN BESAR BAHAN KONSTRUKSI LAINNYA'),
    ('466920', 'PERDAGANGAN BESAR PUPUK DAN PRODUK AGROKIMIA'),
    ('466930', 'PERDAGANGAN BESAR ALAT LABORATORIUM, FARMASI DAN KEDOKTERAN'),
    ('466950', 'PERDAGANGAN BESAR KERTAS DAN KARTON'),
    ('466970', 'PERDAGANGAN BESAR BARANG BEKAS DAN SISA-SISA TAK TERPAKAI (SCRAP)'),
    ('466990', 'PERDAGANGAN BESAR PRODUK LAINNYA YTDL'),
    ('471100', 'PERDAGANGAN ECERAN YANG UTAMANYA MAKANAN, MINUMAN ATAU TEMBAKAU DI TOKO'),
    ('471900', 'PERDAGANGAN ECERAN BERBAGAI MACAM BARANG YANG DIDOMINASI OLEH BARANG BUKAN MAKANAN DAN TEMBAKAU DI TOKO'),
    ('472001', 'PERDAGANGAN ECERAN KHUSUS KOMODITI MAKANAN DARI HASIL PERTANIAN DI TOKO'),
    ('472009', 'PERDAGANGAN ECERAN KHUSUS MAKANAN, MINUMAN DAN TEMBAKAU LAINNYA DI TOKO'),
    ('473000', 'PERDAGANGAN ECERAN KHUSUS BAHAN BAKAR KENDARAAN BERMOTOR'),
    ('474000', 'PERDAGANGAN ECERAN KHUSUS PERALATAN INFORMASI DAN KOMUNIKASI DI TOKO'),
    ('475100', 'PERDAGANGAN ECERAN KHUSUS TEKSTIL DI TOKO'),
    ('475200', 'PERDAGANGAN ECERAN KHUSUS BARANG DAN BAHAN BANGUNAN, CAT DAN KACA DI TOKO'),
    ('475900', 'PERDAGANGAN ECERAN KHUSUS FURNITUR, PERALATAN LISTRIK RUMAH TANGGA, PERALATAN PENERANGAN DAN PERALATAN RUMAH TANGGA LAINNYA DI TOKO'),
    ('476000', 'PERDAGANGAN ECERAN KHUSUS BARANG BUDAYA DAN REKREASI DI TOKO KHUSUS'),
    ('477100', 'PERDAGANGAN ECERAN KHUSUS PAKAIAN, ALAS KAKI DAN BARANG DARI KULIT DI TOKO'),
    ('477200', 'PERDAGANGAN ECERAN KHUSUS BAHAN KIMIA, BARANG FARMASI, ALAT KEDOKTERAN, PARFUM DAN KOSMETIK DI TOKO'),
    ('477300', 'PERDAGANGAN ECERAN KHUSUS BARANG BARU LAINNYA DI TOKO'),
    ('477400', 'PERDAGANGAN ECERAN KHUSUS BARANG BEKAS DI TOKO'),
    ('477700', 'PERDAGANGAN ECERAN BAHAN BAKAR BUKAN BAHAN BAKAR UNTUK KENDARAAN BERMOTOR DI TOKO'),
    ('477800', 'PERDAGANGAN ECERAN BARANG KERAJINAN DAN LUKISAN DI TOKO'),
    ('477900', 'PERDAGANGAN ECERAN KHUSUS BARANG LAINNYA YTDL'),
    ('478100', 'PERDAGANGAN ECERAN KAKI LIMA DAN LOS PASAR KOMODITI HASIL PERTANIAN'),
    ('478200', 'PERDAGANGAN ECERAN KAKI LIMA DAN LOS PASAR MAKANAN, MINUMAN DAN PRODUK TEMBAKAU HASIL INDUSTRI PENGOLAHAN'),
    ('478300', 'PERDAGANGAN ECERAN KAKI LIMA DAN LOS PASAR TEKSTIL, PAKAIAN DAN ALAS KAKI'),
    ('478400', 'PERDAGANGAN ECERAN KAKI LIMA DAN LOS PASAR BAHAN KIMIA, FARMASI, KOSMETIK DAN YBDI'),
    ('478600', 'PERDAGANGAN ECERAN KAKI LIMA DAN LOS PASAR PERLENGKAPAN RUMAH TANGGA'),
    ('478700', 'PERDAGANGAN ECERAN KAKI LIMA DAN LOS PASAR KERTAS, BARANG DARI KERTAS, ALAT TULIS, BARANG CETAKAN, ALAT OLAHRAGA, ALAT MUSIK, ALAT FOTOGRAFI DAN KOMPUTER'),
    ('478800', 'PERDAGANGAN ECERAN KAKI LIMA DAN LOS PASAR BARANG KERAJINAN, MAINAN ANAK-ANAK DAN LUKISAN'),
    ('478920', 'PERDAGANGAN ECERAN KAKI LIMA DAN LOS PASAR BAHAN BAKAR MINYAK, GAS, MINYAK PELUMAS DAN BAHAN BAKAR LAINNYA'),
    ('478940', 'PERDAGANGAN ECERAN KAKI LIMA DAN LOS PASAR BARANG BEKAS PERLENGKAPAN RUMAH TANGGA'),
    ('478990', 'PERDAGANGAN ECERAN KAKI LIMA DAN LOS PASAR BARANG LAINNYA'),
    ('479100', 'PERDAGANGAN ECERAN MELALUI PEMESANAN POS ATAU INTERNET'),
    ('479900', 'PERDAGANGAN ECERAN BUKAN DI TOKO, KIOS, KAKI LIMA DAN LOS PASAR LAINNYA'),
    ('H00000', 'PENGANGKUTAN DAN PERGUDANGAN'),
    ('491000', 'ANGKUTAN JALAN REL'),
    ('492100', 'ANGKUTAN BUS BERTRAYEK'),
    ('492210', 'ANGKUTAN BUS PARIWISATA'),
    ('492290', 'ANGKUTAN BUS TIDAK BERTRAYEK LAINNYA'),
    ('493000', 'ANGKUTAN MELALUI SALURAN PIPA'),
    ('494100', 'ANGKUTAN DARAT BUKAN BUS UNTUK PENUMPANG, BERTRAYEK'),
    ('494200', 'ANGKUTAN DARAT LAINNYA UNTUK PENUMPANG'),
    ('494300', 'ANGKUTAN DARAT UNTUK BARANG'),
    ('494501', 'ANGKUTAN JALAN REL WISATA'),
    ('494509', 'ANGKUTAN JALAN REL LAINNYA'),
    ('501100', 'ANGKUTAN LAUT DALAM NEGERI UNTUK PENUMPANG'),
    ('501130', 'ANGKUTAN LAUT UNTUK WISATA'),
    ('501190', 'ANGKUTAN LAUT DALAM NEGERI UNTUK PENUMPANG SELAIN WISATA'),
    ('501200', 'ANGKUTAN LAUT LUAR NEGERI UNTUK PENUMPANG'),
    ('501300', 'ANGKUTAN LAUT DALAM NEGERI UNTUK BARANG'),
    ('501400', 'ANGKUTAN LAUT LUAR NEGERI UNTUK BARANG'),
    ('502101', 'ANGKUTAN SUNGAI DAN DANAU UNTUK WISATA DAN YBDI'),
    ('502102', 'ANGKUTAN PENYEBERANGAN UNTUK PENUMPANG'),
    ('502200', 'ANGKUTAN SUNGAI, DANAU DAN PENYEBERANGAN UNTUK BARANG'),
    ('511001', 'ANGKUTAN UDARA BERJADWAL UNTUK PENUMPANG'),
    ('511002', 'ANGKUTAN UDARA TIDAK BERJADWAL UNTUK PENUMPANG'),
    ('511009', 'ANGKUTAN UDARA UNTUK PENUMPANG LAINNYA'),
    ('512000', 'ANGKUTAN UDARA UNTUK BARANG'),
    ('521000', 'PERGUDANGAN DAN PENYIMPANAN'),
    ('522000', 'AKTIVITAS PENUNJANG ANGKUTAN'),
    ('530000', 'AKTIVITAS POS DAN KURIR'),
    ('I00000', 'PENYEDIAAN AKOMODASI DAN PENYEDIAAN MAKAN MINUM'),
    ('551100', 'HOTEL BINTANG'),
    ('551200', 'HOTEL MELATI'),
    ('559000', 'PENYEDIAAN AKOMODASI LAINNYA'),
    ('561001', 'RESTORAN DAN RUMAH MAKAN'),
    ('561009', 'PENYEDIAAN MAKANAN DAN MINUMAN LAINNYA'),
    ('J00000', 'INFORMASI DAN KOMUNIKASI'),
    ('580000', 'AKTIVITAS PENERBITAN'),
    ('591000', 'AKTIVITAS PRODUKSI GAMBAR BERGERAK, VIDEO DAN PROGRAM TELEVISI'),
    ('592000', 'AKTIVITAS PEREKAMAN SUARA DAN PENERBITAN MUSIK'),
    ('600000', 'AKTIVITAS PENYIARAN DAN PEMROGRAMAN'),
    ('610001', 'AKTIVITAS TELEKOMUNIKASI DENGAN KABEL, TANPA KABEL DAN SATELIT'),
    ('610002', 'JASA NILAI TAMBAH TELEPONI DAN JASA MULTIMEDIA'),
    ('610009', 'AKTIVITAS TELEKOMUNIKASI LAINNYA YTDL'),
    ('620100', 'AKTIVITAS PEMROGRAMAN KOMPUTER'),
    ('620200', 'AKTIVITAS KONSULTASI KOMPUTER DAN MANAJEMEN FASILITAS KOMPUTER'),
    ('631110', 'AKTIVITAS PENGOLAHAN DATA'),
    ('631120', 'AKTIVITAS HOSTING DAN YBDI'),
    ('631210', 'PORTAL WEB DAN/ATAU PLATFORM DIGITAL TANPA TUJUAN KOMERSIAL'),
    ('631220', 'PORTAL WEB DAN/ATAU PLATFORM DIGITAL DENGAN TUJUAN KOMERSIAL'),
    ('639100', 'AKTIVITAS KANTOR BERITA'),
    ('639900', 'AKTIVITAS JASA INFORMASI LAINNYA YTDL'),
    ('K00000', 'AKTIVITAS KEUANGAN DAN ASURANSI'),
    ('641000', 'PERANTARA MONETER'),
    ('649100', 'SEWA GUNA USAHA DENGAN HAK OPSI'),
    ('649900', 'AKTIVITAS JASA KEUANGAN LAINNYA YTDL, BUKAN ASURANSI DAN DANA PENSIUN'),
    ('650000', 'ASURANSI, REASURANSI DAN DANA PENSIUN, BUKAN JAMINAN SOSIAL WAJIB'),
    ('661001', 'KEGIATAN PENUKARAN VALUTA ASING (MONEY CHANGER)'),
    ('661009', 'AKTIVITAS PENUNJANG JASA KEUANGAN LAINNYA'),
    ('662000', 'AKTIVITAS PENUNJANG ASURANSI DAN DANA PENSIUN'),
    ('L00000', 'REAL ESTAT'),
    ('681101', 'REAL ESTAT PERUMAHAN SEDERHANA PERUMNAS'),
    ('681102', 'REAL ESTAT PERUMAHAN SEDERHANA PERUMNAS TIPE 21'),
    ('681103', 'REAL ESTAT PERUMAHAN SEDERHANA PERUMNAS TIPE 22 S.D. 70'),
    ('681104', 'REAL ESTAT PERUMAHAN MENENGAH, BESAR ATAU MEWAH (TIPE DIATAS 70)'),
    ('681105', 'REAL ESTAT PERUMAHAN FLAT / APARTEMEN'),
    ('681106', 'REAL ESTAT GEDUNG PERBELANJAAN (MAL, PLAZA)'),
    ('681107', 'REAL ESTAT GEDUNG PERKANTORAN'),
    ('681108', 'REAL ESTAT GEDUNG RUMAH TOKO (RUKO) ATAU RUMAH KANTOR (RUKAN)'),
    ('681109', 'REAL ESTAT LAINNYA'),
    ('681200', 'KAWASAN PARIWISATA'),
    ('681300', 'KAWASAN INDUSTRI'),
    ('682000', 'REAL ESTAT ATAS DASAR BALAS JASA (fee) ATAU KONTRAK'),
    ('M00000', 'AKTIVITAS PROFESIONAL, ILMIAH DAN TEKNIS'),
    ('690000', 'AKTIVITAS HUKUM DAN AKUNTANSI'),
    ('702010', 'AKTIVITAS KONSULTASI PARIWISATA'),
    ('702090', 'AKTIVITAS KANTOR PUSAT DAN KONSULTASI MANAJEMEN LAINNYA'),
    ('710000', 'AKTIVITAS ARSITEKTUR DAN KEINSINYURAN; ANALISIS DAN UJI TEKNIS'),
    ('721000', 'PENELITIAN DAN PENGEMBANGAN ILMU PENGETAHUAN ALAM DAN ILMU TEKNOLOGI DAN REKAYASA'),
    ('722000', 'PENELITIAN DAN PENGEMBANGAN ILMU PENGETAHUAN SOSIAL DAN HUMANIORA'),
    ('730000', 'PERIKLANAN DAN PENELITIAN PASAR'),
    ('740000', 'AKTIVITAS PROFESIONAL, ILMIAH DAN TEKNIS LAINNYA'),
    ('750000', 'AKTIVITAS KESEHATAN HEWAN'),
    ('N00000', 'AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI, KETENAGAKERJAAN, AGEN PERJALANAN DAN PENUNJANG USAHA LAINNYA'),
    ('771000', 'AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI MOBIL, BUS, TRUK DAN SEJENISNYA'),
    ('772000', 'AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI BARANG PRIBADI DAN RUMAH TANGGA'),
    ('773020', 'AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI ALAT TRANSPORTASI DARAT BUKAN KENDARAAN BERMOTOR RODA EMPAT ATAU LEBIH'),
    ('773030', 'AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI ALAT TRANSPORTASI AIR'),
    ('773040', 'AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI ALAT TRANSPORTASI UDARA'),
    ('773050', 'AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI MESIN PERTANIAN DAN PERALATANNYA'),
    ('773060', 'AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI MESIN DAN PERALATAN KONSTRUKSI DAN TEKNIK SIPIL'),
    ('773070', 'AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI MESIN KANTOR DAN PERALATANNYA'),
    ('773090', 'AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI MESIN, PERALATAN DAN BARANG BERWUJUD LAINNYA YTDL'),
    ('780000', 'AKTIVITAS KETENAGAKERJAAN'),
    ('791110', 'AKTIVITAS AGEN PERJALANAN WISATA'),
    ('791120', 'AKTIVITAS AGEN PERJALANAN BUKAN WISATA'),
    ('791200', 'AKTIVITAS BIRO PERJALANAN WISATA'),
    ('799000', 'JASA RESERVASI LAINNYA DAN KEGIATAN YBDI'),
    ('823000', 'PENYELENGGARA KONVENSI DAN PAMERAN DAGANG'),
    ('829000', 'AKTIVITAS JASA PENUNJANG USAHA YTDL'),
    ('O00000', 'ADMINISTRASI PEMERINTAHAN, PERTAHANAN DAN JAMINAN SOSIAL WAJIB'),
    ('841000', 'ADMINISTRASI PEMERINTAHAN DAN KEBIJAKAN EKONOMI DAN SOSIAL'),
    ('842000', 'PENYEDIAAN LAYANAN UNTUK MASYARAKAT DALAM BIDANG HUBUNGAN LUAR NEGERI, PERTAHANAN, KEAMANAN DAN KETERTIBAN'),
    ('843000', 'JAMINAN SOSIAL WAJIB'),
    ('P00000', 'PENDIDIKAN'),
    ('851000', 'PENDIDIKAN DASAR DAN PENDIDIKAN ANAK USIA DINI'),
    ('852000', 'PENDIDIKAN MENENGAH'),
    ('853000', 'PENDIDIKAN TINGGI'),
    ('854000', 'PENDIDIKAN LAINNYA'),
    ('855000', 'KEGIATAN PENUNJANG PENDIDIKAN'),
    ('Q00000', 'AKTIVITAS KESEHATAN MANUSIA DAN AKTIVITAS SOSIAL'),
    ('861000', 'AKTIVITAS RUMAH SAKIT'),
    ('862000', 'AKTIVITAS PRAKTIK DOKTER DAN DOKTER GIGI'),
    ('869000', 'AKTIVITAS PELAYANAN KESEHATAN MANUSIA LAINNYA'),
    ('870000', 'AKTIVITAS SOSIAL'),
    ('R00000', 'KESENIAN, HIBURAN DAN REKREASI'),
    ('900001', 'JASA IMPRESARIAT BIDANG SENI'),
    ('900009', 'AKTIVITAS HIBURAN, SENI DAN KREATIVITAS LAINNYA'),
    ('910100', 'PERPUSTAKAAN DAN ARSIP'),
    ('910200', 'MUSEUM DAN OPERASIONAL BANGUNAN DAN SITUS BERSEJARAH'),
    ('930000', 'AKTIVITAS OLAHRAGA DAN REKREASI LAINNYA'),
    ('S00000', 'AKTIVITAS JASA LAINNYA'),
    ('941000', 'AKTIVITAS ORGANISASI BISNIS, PENGUSAHA DAN PROFESI'),
    ('942000', 'AKTIVITAS ORGANISASI BURUH'),
    ('949000', 'AKTIVITAS ORGANISASI KEANGGOTAAN LAINNYA YTDL'),
    ('950000', 'REPARASI KOMPUTER DAN BARANG KEPERLUAN PRIBADI DAN PERLENGKAPAN RUMAH TANGGA'),
    ('960001', 'AKTIVITAS PANTI PIJAT DAN SPA'),
    ('960009', 'AKTIVITAS JASA PERORANGAN LAINNYA'),
    ('T00000', 'AKTIVITAS RUMAH TANGGA SEBAGAI PEMBERI KERJA; AKTIVITAS YANG MENGHASILKAN BARANG DAN JASA OLEH RUMAH TANGGA YANG DIGUNAKAN UNTUK MEMENUHI KEBUTUHAN SENDIRI'),
    ('970000', 'AKTIVITAS RUMAH TANGGA SEBAGAI PEMBERI KERJA DARI PERSONIL DOMESTIK'),
    ('U00000', 'AKTIVITAS BADAN INTERNASIONAL DAN BADAN EKSTRA INTERNASIONAL LAINNYA'),
    ('990000', 'AKTIVITAS BADAN INTERNASIONAL DAN BADAN EKSTRA INTERNASIONAL LAINNYA'),
    ('AA0000', 'RUMAH TANGGA'),
    ('001110', 'RUMAH TANGGA UNTUK PEMILIKAN RUMAH TINGGAL S.D. TIPE 21'),
    ('001120', 'RUMAH TANGGA UNTUK PEMILIKAN RUMAH TINGGAL TIPE DIATAS 21 S.D. 70'),
    ('001130', 'A1.1.3. RUMAH TANGGA UNTUK PEMILIKAN RUMAH TINGGAL TIPE DIATAS 70'),
    ('001210', 'RUMAH TANGGA UNTUK PEMILIKAN FLAT ATAU APARTEMEN S.D. TIPE 21'),
    ('001220', 'RUMAH TANGGA UNTUK PEMILIKAN FLAT ATAU APARTEMEN TIPE DIATAS 21 S.D. 70'),
    ('001230', 'RUMAH TANGGA UNTUK PEMILIKAN FLAT ATAU APARTEMEN TIPE DIATAS 70'),
    ('001300', 'RUMAH TANGGA UNTUK PEMILIKAN RUMAH TOKO (RUKO) ATAU RUMAH KANTOR (RUKAN)'),
    ('002100', 'RUMAH TANGGA UNTUK PEMILIKAN MOBIL RODA EMPAT'),
    ('002200', 'RUMAH TANGGA UNTUK PEMILIKAN SEPEDA BERMOTOR'),
    ('002300', 'RUMAH TANGGA UNTUK PEMILIKAN TRUK DAN KENDARAAN BERMOTOR RODA ENAM ATAU LEBIH'),
    ('002900', 'RUMAH TANGGA UNTUK PEMILIKAN KENDARAAN BERMOTOR LAINNYA'),
    ('003100', 'RUMAH TANGGA UNTUK PEMILIKAN FURNITUR DAN PERALATAN RUMAH TANGGA'),
    ('003200', 'RUMAH TANGGA UNTUK PEMILIKAN TELEVISI, RADIO, DAN ALAT ELEKTRONIK'),
    ('003300', 'RUMAH TANGGA UNTUK PEMILIKAN KOMPUTER DAN ALAT KOMUNIKASI'),
    ('003900', 'RUMAH TANGGA UNTUK PEMILIKAN PERALATAN LAINNYA'),
    ('004120', 'RUMAH TANGGA UNTUK KEPERLUAN MULTIGUNA BERAGUNAN RUMAH TINGGAL S.D TIPE 21'),
    ('004130', 'RUMAH TANGGA UNTUK KEPERLUAN MULTIGUNA BERAGUNAN RUMAH TINGGAL TIPE DIATAS 21 S.D. 70'),
    ('004140', 'RUMAH TANGGA UNTUK KEPERLUAN MULTIGUNA BERAGUNAN RUMAH TINGGAL TIPE DIATAS 70'),
    ('004150', 'RUMAH TANGGA UNTUK KEPERLUAN MULTIGUNA BERAGUNAN APARTEMEN S.D TIPE 21'),
    ('004160', 'RUMAH TANGGA UNTUK KEPERLUAN MULTIGUNA BERAGUNAN APARTEMEN TIPE 22 S.D 70'),
    ('004170', 'RUMAH TANGGA UNTUK KEPERLUAN MULTIGUNA BERAGUNAN APARTEMEN TIPE DIATAS 70'),
    ('004180', 'RUMAH TANGGA UNTUK KEPERLUAN MULTIGUNA BERAGUNAN RUKO/RUKAN'),
    ('004190', 'RUMAH TANGGA UNTUK KEPERLUAN MULTIGUNA LAINNYA'),
    ('004900', 'RUMAH TANGGA UNTUK KEPERLUAN YANG TIDAK DIKLASIFIKASIKAN DI TEMPAT LAIN'),
    ('BB0000', 'BUKAN LAPANGAN USAHA LAINNYA'),
    ('009000', 'BUKAN LAPANGAN USAHA LAINNYA')
ON CONFLICT (code) DO NOTHING;
